site_name: Niko Docs
site_url: https://joanico.github.io/makdocs/
# ida nee kria navbar ka menu
nav:
    - Python Baziku:
        - 'Python Introdusaun': 'python_overview.md'
        - 'Python Kria Enviromentu': 'python_environment_setup'
        - 'Python Sintase': 'python_syntax.md'
        - 'Python Tipu Data': 'python_data_type.md'
        - 'Python Variabel': 'python_variables.md'
        - 'Python Tuple': 'python_tuples.md'
        - 'Python Mutable no Immutable': 'python_mutable_immutable.md'
        - 'Python Set': 'python_set.md'
        - 'Python Slice': 'python_list_slicing.md'
    - Python Avansadu:
        - 'Python Tutorial Avansadu': 'python_advanced_tutorials.md'
    - Python Tutorial Seluk:
        - 'Python Tutorial Seluk': 'python_other_tutorials.md'
    - Konaba:
        - 'Referensia': 'about.md'
#Kria tema 
theme:
    name: readthedocs #iha nebe ita bele troka readthedocs tema ba mkdocs
    nav_style: red
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

plugins:
  - search
  - macros

#Kria extensaun markdown        
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    
# Kria extra css bele troka style
extra_css:
    - extra_css/extra.css
    
# Ida nee uza css wainhira atu deploy ba github    
extra_css: [extra_css/extra.css]
