site_name: My Docs
nav:
- Home: 'index.md'
- User Guide:
    - 'Tablet Set up': 'tablets.md'
    - 'Mobile Set up': 'mobile.md'
    - 'Python Tutorial': 'python.md'
    - 'Install Adb': 'Install_adb.md'
- About:
    - 'Referensia': 'about.md'
theme: readthedocs
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
